services:
  grpc-server:
    #build the grpc client
    build:
      context: .
      dockerfile: Dockerfile.server

    # mount the current directory to /app in the container to reflect changes outside the container
    volumes:
      - ./server:/app
      - ./proto:/app/proto
      - ./generated:/app/generated
    container_name: grpc_server
    ports:
      - "50051:50051"
    networks:
      - grpc-net

  grpc-client:
    #build the grpc client
    build:
      context: .
      dockerfile: Dockerfile.client

    # mount the current directory to /app in the container to reflect changes outside the container
    volumes:
      - ./client:/app
      - ./proto:/app/proto
      - ./generated:/app/generated
    container_name: grpc_client
    
    # Uncomment the following line to keep the container running for debugging purposes
    #command: tail -f /dev/null

    depends_on:
      - grpc-server
    networks:
      - grpc-net

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile.rest


    container_name: rest_gateway
    depends_on:
      - grpc-server
    ports:
      - "8000:8000"
    networks:
      - grpc-net

  graphql-gateway:
    build:
      context: .
      dockerfile: Dockerfile.graphql


    container_name: graphql_gateway
    depends_on:
      - grpc-server
    ports:
      - "9000:8000"
    networks:
      - grpc-net



#create a network for the grpc services
networks:
  grpc-net:
    driver: bridge
